-- Add media_url column to content_calendar for pre-generated Supabase Storage images
ALTER TABLE content_calendar
  ADD COLUMN IF NOT EXISTS media_url TEXT;

-- Create public storage bucket for campaign media (images generated by Google Imagen)
INSERT INTO storage.buckets (id, name, public)
VALUES ('campaign-media', 'campaign-media', true)
ON CONFLICT (id) DO NOTHING;
